### ISSUE TITLE
Error HTTP 404

### ISSUE THREAD

**Issue by stefan0704** [phlegx/redmine_gitlab_hook#51]
Hello, so i installed this plugin on my redmine server, but when i make a test on the weebhook, it returns me:

Hook executed successfully but returned HTTP 404 <!DOCTYPE html> <html> <head> <meta charset="utf-8" /> <title>Redmine 404 error</title> <style> body {font-family: "Trebuchet MS", Georgia, "Times New Roman", serif; color: #303030; margin: 10px;} h1 {font-size:1.5em;} p {font-size:0.8em;} </style> </head> <body> <h1>Page not found</h1> <p>The page you were trying to access doesn't exist or has been removed.</p> <p><a href="javascript:history.back()">Back</a></p> </body> </html>

If you can help me i will apreciate it.

Thanks

**Comment by mtwango** [comment]
Yeah, having the same problem here. I think it has something to do with API key, since URL without 'key' parameter is giving proper 403.

**Comment by mtwango** [comment]
I was actually pretty stupid.  First of all, I was calling it with GET instead of post and then I hadnt enough parameters in POST.
I was calling it with repository_name only and not project_id, so calling 
`{redmine_installation_url}/gitlab_hook?key={redmine_repository_API_key}&project_id={redmine_project_identifier}&repository_name={repository_name}` solved if ror me.
